# Generated by Django 3.1.5 on 2021-01-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='menu_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
