# Generated by Django 3.1.5 on 2021-02-02 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
